name: 'Code coverage, quality check and Pypi upload'
on:
  push:
    branches:
      - master
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install system dependencies
        run: |
          sudo apt-get install apt-rdepends
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Generate coverage report
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .[test]
          python -m pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: '${{ secrets.CODECOV_TOKEN }}'
          file: ./coverage.xml
          flags: unittests
  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install pytest
          pytest
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.13.4
        continue-on-error: true
        with:
          reporter: github-pr-review
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
      - name: Build and publish
        env:
          TWINE_USERNAME: '${{ secrets.PYPI_USERNAME }}'
          TWINE_PASSWORD: '${{ secrets.PYPI_PASSWORD }}'
        run: |
          python setup.py sdist bdist_wheel
          twine upload dist/*
